### ISSUE TITLE
Should add an install section to the Readme from the info we have discovered

### ISSUE THREAD

**Issue by djarami** [hypersad/atom#10]
@hypersad I think you should add a couple of lines for the Install process in the readme and gather it from the other issue(s) that we already did the discovery/testing work and are now closed.

**Comment by hypersad** [comment]
Currently i'm little busy. Can you tell me, what I need to add to README? Some quotes, or your words.

**Comment by djarami** [comment]
I would add two parts:

- Create install package.  Under ~/atom directory
node script/build --create-debian-package

- Install package from command line.  Under ~/atom/out
sudo dpkg -i atom-armhf.deb 
if you error out with missing packages  Package gvfs-bin is not installed, you will need to install those packages separately and then run the install again.

- Install via UI, install the following packages and then run gdebi installer from UI
sudo apt-get -f install
sudo apt-get install gdebi

**Comment by hypersad** [comment]
Added. Can I close this issue?

**Comment by djarami** [comment]
looks good, closing issue.
