### ISSUE TITLE
question(s) about packages

### ISSUE THREAD

**Issue by kylepwarren** [hypersad/atom#2]
for this arm fork, 
     will I be able to download packages normally? 

Have you noticed any packages that have compatibility problems?

Do I need to turn off updates / be careful about [package]updates?

**Comment by hypersad** [comment]
1. I don't know what deal with installing packages during install, for some reasons (I don't touch packages / package installation process) they are missing (maybe, only for me), so I wrote a little script that downloads them again. I think, if you're update them, they're didn't broke. 

2. I noticed, that tree-view package doesn't work. It's thrown error on start.

3. I don't think so.

**Comment by hypersad** [comment]
Hello, tree-view package issue was fixed in atom.firstboot.sh.

**Comment by curiousercreative** [comment]
@hypersad Can we close this issue? It seems to be resolved.

**Comment by djarami** [comment]
I guess one remaining question I have is do we checking my updates package.json or do we live with the atom.firstboot.sh.  I don't believe we want to have this multi pass build/packaging and be able to provide a downloadable built package.  Thoughts ?

**Comment by curiousercreative** [comment]
@djarami my previous attempt to build with your `package.json` didn't succeed. Has it been updated? Can I suggest that you submit a pull request or post it here again and I'll submit one for you (assuming it is working).
