### ISSUE TITLE
Atom build should be a one-step process and succeed on first try

### ISSUE THREAD

**Issue by curiousercreative** [hypersad/atom#4]
The current build process is:
1. run `node script/build`
1. run `sh atom.firstboot.sh`

**Comment by djarami** [comment]
I'm currently working on this one.  Shifting to testing it from a clean git clone.  
- run `git clone .....`
- run `node script/build`

Will be making modifications to package.json - maybe removing some git related packages to help avoid the crash when opening a git managed directory - Issue #6

**Comment by djarami** [comment]
I found that when I try to use my package.json with a newly cloned build, the build breaks.  When you run the atom.firstboot script it says that these packages are already in the atom package.   But what's weird is that she. You run atom after the build the packages don't seem to be enabled or something.    More investigation to come.

**Comment by djarami** [comment]
Latest updates:  On first pass
- I compared package.json and atom.firstbuild.sh and they both have the same packages.  Only difference is that package.json specifi are es the package version and atom.firstbuild doesn't for the exception of treeview.
- I verified that the out directory has all the packages in there.

I'm suspecting that atom.firstbuild.sh comes through and pulls in the latest of each of these modules.  

@curiousercreative @hypersad 
I'm looking for some command in `apm` that will dump me the version for all the packages that are in the out directory.

**Comment by hypersad** [comment]
Hello! I think that the merging packageDepenencies with dependencies or packing packages into git repository isn't good idea, because we didn't get the newest versions of packages, and user spend much longer time for installing, then updating all packages (like 2x install). So, i want to delete all packageDependencies, what you think about it, guys?

**Comment by djarami** [comment]
I've been doing extensive analysis on this and the build process and atom.firstboot totally duplicate what they are doing.  Whatever the build process does with those packages does nothing useful except take build time.  whatever atom.firstboot is doing, apm install - which reinstalls each of the packages, seems to do the right thing.  I compared each of the versions from the build and compared it to what the script installs and they are exactly the same.
At this point, your suggestion about removing the packageDependencies section and letting the atom.firstboot.sh do the installing the packages is not a bad one.

Personally, I don't like not understanding why it isn't working right, but to me, it smells like an apm/packagin bug in the build process step.  apm clearly says those packages are already there but somehow the loader is not starting/opening them until after it is re-done with the atom.firstboot.sh is run.  Honestly, I would just add the atom.firstboot.sh as part of the build and see if that works.

**Comment by hypersad** [comment]
We can try to make shell script like a
node script/build
atom.firstboot.sh

**Comment by djarami** [comment]
call it `build.sh` ?
If it does the job, we should go for it.  We need more expertise on the packaging issue and to be honest, we've spent too much time on this.  I would rather finish up figuring out how to do the install from the command line.  Right now, I've only know how to do it from the GUI.

**Comment by djarami** [comment]
Ok, re-cloned and did the two things one after another and it worked !!!!!
node script/build
atom.firstboot.sh

![image](https://cloud.githubusercontent.com/assets/4624027/25597213/85bae2a2-2e9b-11e7-99ef-7b7ea9adc8cf.png)

Next we have to be able to do the deb package install from the command line.  
Maybe a new ticket for that one.

Here is the build.sh I created.  Need to make sure that it has the +x attribute:

```
echo "Starting build for Atom"
node script/build
echo "-----------------------------"
echo "Starting packaging atom.firstboot.sh"
chmod +x atom.firstboot.sh
./atom.firstboot.sh
```

**Comment by curiousercreative** [comment]
Also marking this as resolved!

**Comment by curiousercreative** [comment]
Note to self, we should update the README.md for the streamlined build and install.
