### ISSUE TITLE
Atom build should not require omitting "git-utils" from package.json to prevent crashes

### ISSUE THREAD

**Issue by curiousercreative** [hypersad/atom#6]
While our ARM Atom build is functional, it will crash in the following scenarios:
1. without another file open, attempt to open a file that is within a git repo (File > Open File) which will attempt to load the git repo folder into the tree view. If the tree view already has another folder active, then this scenario will actually pass.
1. attempt to add a project folder to the tree view or open a folder that is a git repo (File > Open Folder, File > Add Project Folder)

Both result in not so useful error alerts `The editor has crashed` and error messages in window running Atom process `Failed to get crash dump id. Report Id:`

**Comment by hypersad** [comment]
Currently try to work at this error.

**Comment by daphil19** [comment]
So I was able to successfully open a git repo from a clean build and removing the `git-utils` package from `package.json`. It might be a good idea to snoop around there and see if there is a version out that fixes this.

**Comment by curiousercreative** [comment]
@hypersad I can confirm that the crash is related to the tree view.

@daphil19 that sounds promising. I'd like to try and reproduce your success. Can you share your `package.json` and any other changes required via a pull request or paste in here?

**Comment by djarami** [comment]
I've had similar nice results but something doesn't seem to build right from a clean git clone extract.  So I'm still working on that too.  @daphil19 I'll take your package.json too if you can share it so I can give it a try.  Otherwise, I'll just remove the git-útiles package and see how that goes.

**Comment by daphil19** [comment]
@curiousercreative @djarami I created PR #8 for you to reproduce. Left a WIP tag on it because removing the package feels kindor dirty to me. As per the comments on the PR, I think we should look into finding a fix for `git-utils` instead of removing it.

**Comment by curiousercreative** [comment]
@daphil19 just did a clean build with your pull request and I can confirm that it solves this issue!!! I'm going to rename this issue.

**Comment by curiousercreative** [comment]
@hypersad @daphil19 ok, so now this issue is for us to figure out why `git-utils` causes crashes and hopefully revert PR https://github.com/hypersad/atom/pull/8

**Comment by hypersad** [comment]
Okay, finally I'm done working with my tablet and successfully test your Pgit-R, and looks like it works. Can somebody explain me,what we loose without git-utils package?

**Comment by hypersad** [comment]
Good news everyone! I could open a git repo folder with git-utils. Because nobody answered me for my previous question, I can't fully test it. Can someone else test it too? You can only update package.json.

**Comment by hypersad** [comment]
Where is all testers? :'(

**Comment by djarami** [comment]
Sorry. Burning the midnight oil with my work stuff. 
I tried a few things and put my results there. 

Tell me again what you want tested and I'll give it a go tomorrow.  Will it include your new packaging idea ?

**Comment by hypersad** [comment]
I'll read git-utils page and find issue about crashing, I'm not sure that it is our trouble, but people said that new fixes included in master branch only (means there is no release with those fix), so I replaced our ~4.2 version with ^5.0.0 (^ means latest version, how I know)

**Comment by hypersad** [comment]
@djarami I'M CALLING!
@curiousercreative I'M CALLING!
@daphil19 I'M CALLING!
TIME TO TEST!

Please, use new package.json for building and try to open a git repository.

**Comment by curiousercreative** [comment]
@hypersad I'll likely be able to test tomorrow.

**Comment by djarami** [comment]
I'll try later today.

**Comment by djarami** [comment]
@hypersad is this the new package.json without the dependencies ?

**Comment by hypersad** [comment]
@djarami yep

**Comment by djarami** [comment]
I did the build last night, called the atom.firstboot.sh and created the debian package.

I got this when I tried to launch atom after building all that.

![image](https://cloud.githubusercontent.com/assets/4624027/25580044/5b234142-2e4b-11e7-8ce7-02b329320f14.png)

I'll have to start again and then do the launch of atom after the build and then do the atom.firstboot.sh to see if that fixes the problem.

**Comment by curiousercreative** [comment]
@hypersad Прекрасно! Build succeed on the first try with `node script/build` and everything seems fully functional (including git repos) upon first boot! Feel free to keep discussions going in here, but as the original poster, I'm marking this as resolved.
